### ISSUE TITLE
Immortal invalid events blocks the queue

### ISSUE THREAD

**Issue by Fryuni** [croct-tech/sdk-js#104]
## 🐞 Bug report
A combination of two facts causes the bug:
* Events tracked always go to WebSocket connections with the token used to track them.
* WebSocket connections with invalid tokens are blocked by the authentication system.

When an event is tracked with an invalid token it won't be delivered and as such will be added back to the queue to be retried. The connection required for such an event will never succeed, so the event will never be delivered, causing the queue to be blocked permanently (or until the browser clears the local storage).

### Steps to reproduce
Please provide a minimal code snippet and the detailed steps for reproducing the issue.

1. Generate a valid token
1. Make it invalid for authentication but still a valid JWT, like changing the signature.
1. Track an event using the tampered token
1. Track an event with the original valid token
2. Neither event is ever delivered

### Expected behavior
The undeliverable event should be discarded after some determined number of attempts.

Ideally, the event would be dropped based on the type of the error, so they would not be dropped on network connection problems, but since browsers don't expose the error cause we have to compromise that some data might be lost if a network connection problem lasts long enough.

### Additional context
[IPv4](https://www.rfc-editor.org/rfc/inline-errata/rfc791.html) has a Time to Live field for a similar purpose:
> Time to Live:  8 bits
> This field indicates the maximum time the datagram is allowed to remain in the internet system.  If this field contains the value zero, then the datagram must be destroyed. [...]
>  The intention is to cause undeliverable datagrams to be discarded, and to bound the maximum datagram lifetime.

**Comment by Fryuni** [comment]
For the record. We fixed this problem by not refusing such messages. Instead, we now receive those connections and ignore the events that are sent through them.

By the [specification for WebSocket clients](https://www.w3.org/TR/websockets/#closeWebSocket), an unauthorized error and a network error should be indistinguishable by the calling script (the SDK)

> User agents must not convey any failure information to scripts in a way that would allow a script to distinguish the following situations:
> - [...]
> - A server that did not complete the opening handshake.
> - A WebSocket server that abruptly closed the connection after successfully completing the opening handshake.

By choosing to accept the connections and the messages we can handle all such cases on our services without requiring any update on the clients. This also allows us to centralize the notification of such problems instead of just failing the connection at the end user's browser.

**Comment by marcospassos** [comment]
Thanks, @Fryuni!
