### ISSUE TITLE
Handle silent WebSocket connection break

### ISSUE THREAD

**Issue by Fryuni** [croct-tech/sdk-js#83]
## 🐞 Bug report
Virtual sockets can be broken silently, the browser do not identify that the connection is closed and therefore don't close or even notify the WebSocket handle.  
This happens, for example, when using a VPN that has multiple servers, the exit server can be changed without and the virtual connections made on top of it will break.

### Steps to reproduce
_The example commands are for NordVPN, but tested with NortonVPN_
1. Connect to a VPN: `nordvpn connect us`
2. Open the Playground
3. Change the server: `nordvpn connect uk`
4. The connection will be there, but no messages are truly being sent

### Expected behavior
The connection should be dropped and a new one should be created using the new routing.

### Screenshots
![image](https://user-images.githubusercontent.com/11063910/83646760-7d087e80-a58a-11ea-8ef1-3e6aabc95be0.png)

### Additional context
If you set your VPN to not handle connection during server change this behavior apparently becomes random. But this is not recommended anyway as it programs to bypass the VPN and open a raw connection during this window. On NordVPN this is done exactly be disabling the killswitch `nordvpn set killswitch off`

**Comment by Fryuni** [comment]
Possible solution, recycle channel after X retries

**Comment by marcospassos** [comment]
Closing this as we have completely refactored the SDK to use HTTP instead of WebSockets, so this is no longer an issue.
